- **进程线程协程使用场景**  
  线程和协程多使用在I/O操作场景，而进程多使用在计算场景。
  线程存在GIL问题（GIL是一个互斥锁，它防止多个线程同时执行Python字节码。这个锁是必要的，主要是因为CPython的内存管理不是线程安全的），当线程用于计算密集型的任务时其对于计算密集型的任务没有什么帮助。

- **线程和协程区别**  
  协程在线程中实现调度。你可以理解为它是 「微线程」 。它的调度不来自于CPU，而是完全来自于用户控制（可以理解为用代码控制流程）。
  协程的执行效率非常高，它的切换不是线程切换，没有线程切换的开销。而且只要线程越多，协程的性能优势就越明显。
  协程不需要多线程的锁机制，只需要判断状态即可。不过协程本身无法利用多核CPU，因为它基于线程，而线程又依赖于进程。
  
+ **主线程捕获子线程异常** 
  一个线程拥有自己独立的上下文和调用栈，如果该线程（调用栈）中 抛出异常之后，调用方是无法捕获的。
  + 方法一：
    sys.exc_info()可以返回当前的异常，作为一个属性保存下来，然后在线程的join方法中重新抛出异常。
```python
    #! python3
    #-*- coding:utf-8 --
    import threading
    from _ast import Raise
    from time import sleep
    class ExcThread(threading.Thread):
        def __init__(self,group=None, target=None, name=None,
                     args=(), kwargs=None, verbose=None):
            threading.Thread.__init__(self, group, target, name, args, kwargs)
            if kwargs is None:
                kwargs = {}
            self.__target = target
            self.__args = args
            self.__kwargs = kwargs
        def run(self):
            self.exc = None
            try:
                # Possibly throws an exception
                if self.__target:
                    self.__target(*self.__args, **self.__kwargs)
            except Exception as e:
                import sys
                self.exc = sys.exc_info()
            finally:
                # Avoid a refcycle if the thread is running a function with
                # an argument that has a member that points to the thread.
                del self.__target, self.__args, self.__kwargs
        # Save details of the exception thrown but don't rethrow,
        # just complete the function
        def join(self):
            threading.Thread.join(self)
            if self.exc:
                msg = "Thread '%s' threw an exception: %s" % (self.getName(), self.exc[1])
                new_exc = Exception(msg)
                raise new_exc.with_traceback(self.exc[2])
    def test1():
        for i in range(2):
            print('{},{}'.format(threading.current_thread().getName(), i))
        raise RuntimeError('success')
    def test2():
        for i in range(5):
            print('{},{}'.format(threading.current_thread().getName(), i))
            sleep(1)
    if __name__ == '__main__':
        while True:
            th = ExcThread(target=test1)
            th2 = ExcThread(target=test2)
            try:
                th.start()
                th2.start()
                th.join()
                th2.join()
            except Exception as e:
                print(e)
                break
        print('Done')
```
